INSERT INTO FEATURE (ID, IDENTIFICATION, REQUIRED_SOFTWARE, PROHIBITED_SOFTWARE, REQUIRED_HARDWARE, PROHIBITED_HARDWARE) VALUES (4, 'Test_A', 'A B', 'E', 'C D', 'F')
INSERT INTO FEATURE (ID, IDENTIFICATION, REQUIRED_SOFTWARE, PROHIBITED_SOFTWARE, REQUIRED_HARDWARE, PROHIBITED_HARDWARE) VALUES (5, 'Test_B', 'A', 'B E', 'C', 'D F')
INSERT INTO FEATURE (ID, IDENTIFICATION, REQUIRED_SOFTWARE, PROHIBITED_SOFTWARE, REQUIRED_HARDWARE, PROHIBITED_HARDWARE) VALUES (6, 'Test_C', 'E', 'A', 'F', 'B')

INSERT INTO VEHICLE (ID, IDENTIFICATION, INSTALLED_SOFTWARE_HARDWARE) VALUES (1, 'VIN_1', 'A B C D')
